// <auto-generated />
using System;
using EngConnect.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EngConnect.Repositories.Migrations
{
    [DbContext(typeof(EngConnectContext))]
    [Migration("20251221123601_RefreshToken")]
    partial class RefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EngConnect.Entities.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("application_user", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("AssignmentId")
                        .HasName("assignment_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("SessionId");

                    b.ToTable("assignment", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ChatMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("content_type");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("sender_id");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("MessageId")
                        .HasName("chatmessage_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex("ThreadId", "CreatedAt")
                        .HasDatabaseName("ix_chat_message_thread_created");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ChatParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ParticipantId"));

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_read_at");

                    b.Property<int>("ThreadId")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("ParticipantId")
                        .HasName("chatparticipant_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("ThreadId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_chat_participant_thread_user");

                    b.ToTable("chat_participant", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ChatThread", b =>
                {
                    b.Property<int>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("thread_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ThreadId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("ThreadId")
                        .HasName("chatthread_pkey");

                    b.ToTable("chat_thread", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IntroVideo")
                        .HasColumnType("text")
                        .HasColumnName("intro_video");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Level")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("level");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer")
                        .HasColumnName("total_sessions");

                    b.Property<string>("TutorId")
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("CourseId")
                        .HasName("course_pkey");

                    b.HasIndex("TutorId");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.CourseModule", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("ModuleId")
                        .HasName("coursemodule_pkey");

                    b.HasIndex("CourseId");

                    b.ToTable("course_module", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.CourseReview", b =>
                {
                    b.Property<int>("CourseReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("CourseReviewId")
                        .HasName("course_review_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("course_review", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("SessionsPurchased")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_purchased");

                    b.Property<int>("SessionsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_remaining");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("Id")
                        .HasName("enrollment_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("LearnerId");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lesson_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LessonId"));

                    b.Property<string>("ContentUrl")
                        .HasColumnType("text")
                        .HasColumnName("content_url");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LessonType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lesson_type");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("LessonId")
                        .HasName("lesson_pkey");

                    b.HasIndex("ModuleId");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("Sessions")
                        .HasColumnType("integer")
                        .HasColumnName("sessions");

                    b.HasKey("ItemId")
                        .HasName("orderitem_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("LearnerId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("PaymentId")
                        .HasName("payment_pkey");

                    b.HasIndex("OrderId");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("jwt_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refreshtoken_pkey");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_refreshtoken_token");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("ReviewId")
                        .HasName("review_pkey");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SessionId");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_time");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text")
                        .HasColumnName("meeting_link");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("session_number");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'booked'::character varying");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("SessionId")
                        .HasName("session_pkey");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("graded_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'not_submitted'::character varying");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("SubmissionId")
                        .HasName("submission_pkey");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("LearnerId");

                    b.ToTable("submission", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorProfile", b =>
                {
                    b.Property<string>("TutorId")
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.Property<bool>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("approved");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvFile")
                        .HasColumnType("text")
                        .HasColumnName("cv_file");

                    b.Property<string>("DemoVideo")
                        .HasColumnType("text")
                        .HasColumnName("demo_video");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TutorId")
                        .HasName("tutorprofile_pkey");

                    b.ToTable("tutor_profile", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_booked");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_time");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("ScheduleId")
                        .HasName("tutorschedule_pkey");

                    b.HasIndex("AvailabilityId");

                    b.HasIndex("TutorId");

                    b.ToTable("tutor_schedule", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorWeeklyAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("AvailabilityId")
                        .HasName("tutorweeklyavailability_pkey");

                    b.HasIndex("TutorId");

                    b.ToTable("tutor_weekly_availability", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.WithdrawRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("request_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<string>("PayoutInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payout_info");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("update_date");

                    b.HasKey("RequestId")
                        .HasName("withdrawrequest_pkey");

                    b.HasIndex("TutorId");

                    b.ToTable("withdraw_request", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Assignment", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("assignment_course_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.Session", "Session")
                        .WithMany("Assignments")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("assignment_session_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ChatMessage", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("chatmessage_sender_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatmessage_thread_id_fkey");

                    b.Navigation("Sender");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ChatParticipant", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ChatThread", "Thread")
                        .WithMany("Participants")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatparticipant_thread_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("chatparticipant_user_id_fkey");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Course", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.TutorProfile", "Tutor")
                        .WithMany("Courses")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("course_tutor_id_fkey");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.CourseModule", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Course", "Course")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("coursemodule_course_id_fkey");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.CourseReview", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Course", "Course")
                        .WithMany("CourseReviews")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("course_review_course_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Learner")
                        .WithMany("CourseReviews")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("course_review_learner_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Enrollment", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("enrollment_course_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Learner")
                        .WithMany("Enrollments")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("enrollment_learner_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Lesson", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.CourseModule", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .HasConstraintName("lesson_module_id_fkey");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.OrderItem", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Course", "Course")
                        .WithMany("OrderItems")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("orderitem_course_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.Orders", "Order")
                        .WithMany("Orderitems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("orderitem_order_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Orders", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Learner")
                        .WithMany("Orders")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("orders_learner_id_fkey");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Payment", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Orders", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("payment_order_id_fkey");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.RefreshToken", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refreshtoken_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Review", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Learner")
                        .WithMany("Reviews")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("review_learner_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.Session", "Session")
                        .WithMany("Reviews")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("review_session_id_fkey");

                    b.Navigation("Learner");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Session", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Enrollment", "Enrollment")
                        .WithMany("Sessions")
                        .HasForeignKey("EnrollmentId")
                        .IsRequired()
                        .HasConstraintName("session_enrollment_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.TutorSchedule", "Schedule")
                        .WithMany("Sessions")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("session_schedule_id_fkey");

                    b.Navigation("Enrollment");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Submission", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("submission_assignment_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Learner")
                        .WithMany("Submissions")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("submission_learner_id_fkey");

                    b.Navigation("Assignment");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorProfile", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", "Tutor")
                        .WithOne("TutorProfile")
                        .HasForeignKey("EngConnect.Entities.Entities.TutorProfile", "TutorId")
                        .IsRequired()
                        .HasConstraintName("tutorprofile_tutor_id_fkey");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorSchedule", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.TutorWeeklyAvailability", "Availability")
                        .WithMany("Tutorschedules")
                        .HasForeignKey("AvailabilityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("tutorschedule_availability_id_fkey");

                    b.HasOne("EngConnect.Entities.Entities.TutorProfile", "Tutor")
                        .WithMany("TutorSchedules")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("tutorschedule_tutor_id_fkey");

                    b.Navigation("Availability");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorWeeklyAvailability", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.TutorProfile", "Tutor")
                        .WithMany("TutorWeeklyAvailabilities")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tutorweeklyavailability_tutor_id_fkey");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.WithdrawRequest", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.TutorProfile", "Tutor")
                        .WithMany("WithdrawRequests")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("withdrawrequest_tutor_id_fkey");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EngConnect.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatParticipants");

                    b.Navigation("CourseReviews");

                    b.Navigation("Enrollments");

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("Submissions");

                    b.Navigation("TutorProfile");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.ChatThread", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Course", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("CourseModules");

                    b.Navigation("CourseReviews");

                    b.Navigation("Enrollments");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.CourseModule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Enrollment", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Orders", b =>
                {
                    b.Navigation("Orderitems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.Session", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorProfile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TutorSchedules");

                    b.Navigation("TutorWeeklyAvailabilities");

                    b.Navigation("WithdrawRequests");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorSchedule", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("EngConnect.Entities.Entities.TutorWeeklyAvailability", b =>
                {
                    b.Navigation("Tutorschedules");
                });
#pragma warning restore 612, 618
        }
    }
}
